### ISSUE TITLE
Resolution is hard-coded in compile_exitpoint.sh

### ISSUE THREAD

**Issue by kaiyuan-cheng** [jzhang512/Containerized_SHiELD_Workflow#1]
Resolution should vary with configurations. Could you revise it?
https://github.com/jzhang512/Containerized_SHiELD_Workflow/blob/83ff819945158998d134c667f8f8704395cd1100/preprocessing/image_build/compile_exitpoint.sh#L21

**Comment by jzhang512** [comment]
Sorry about that. Good catch
